name: sistema_asistencias

services:
  db:
    image: mysql:8.0
    container_name: asistencias_mysql
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: America/Lima
      MYSQL_DATABASE: "${MYSQL_DB:?Error: define MYSQL_DB en .env}"
      MYSQL_USER: "${MYSQL_USER:?Error: define MYSQL_USER en .env}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?Error: define MYSQL_PASSWORD en .env}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?Error: define MYSQL_ROOT_PASSWORD en .env}"
    volumes:
      - asistencias_mysql_data:/var/lib/mysql
    networks:
      - asistencias_net
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=\"$$MYSQL_ROOT_PASSWORD\" mysqladmin ping -h localhost -u root"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: ./backend
    container_name: asistencias_backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8082:8000"
    volumes:
      - ./backend:/app
    environment:
      TZ: America/Lima
      MYSQL_SERVER: db
      MYSQL_PORT: 3306
      MYSQL_DB: "${MYSQL_DB:?Error: define MYSQL_DB en .env}"
      MYSQL_USER: "${MYSQL_USER:?Error: define MYSQL_USER en .env}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?Error: define MYSQL_PASSWORD en .env}"
      AGENTE_HTTP_URL: "${AGENTE_HTTP_URL:-http://192.168.0.104:5050}"
      AGENTE_SECRET_TOKEN: "${AGENTE_SECRET_TOKEN:?Error: define AGENTE_SECRET_TOKEN en .env}"
      PUBLIC_URL: "${PUBLIC_URL:-http://${SERVER_HOST:-localhost}:8080}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asistencias_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://${SERVER_HOST:-localhost}:8080}
    container_name: asistencias_frontend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - asistencias_net

networks:
  asistencias_net:
    driver: bridge

volumes:
  asistencias_mysql_data:

